systemProp.nebula.features.coreLockingSupport=true
org.gradle.caching=true
org.gradle.configuration-cache=true

# Disable Kotlin FUS (Feature Usage Statistics) to fix configuration cache issue
# See: https://youtrack.jetbrains.com/issue/KT-69078/Gradle-Add-option-to-disable-FUS-Service
kotlin.internal.collectFUSMetrics=false